[workspace]
members = ["download", "rustup", "rustup-macros"]

[workspace.dependencies]
anyhow = "1.0.69"
derivative = "2.2.0"
enum_dispatch = "0.3.11"
fs_at = "0.1.6"
lazy_static = "1"
once_cell = "1.18.0"
opentelemetry = { version = "0.20.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.13.0" }
proptest = "1.1.0"
rustup-macros = { path = "rustup-macros" }
tempfile = "3.7"
termcolor = "1.2"
thiserror = "1.0"
tokio = { version = "1.26.0", default-features = false, features = [
    "rt-multi-thread",
] }
tracing = "0.1"
tracing-opentelemetry = { version = "0.20.0" }
tracing-subscriber = "0.3.16"
url = "2.4"
walkdir = "2"

[profile.release]
codegen-units = 1
lto = true

# Reduce build time by setting proc-macro crates non optimized.
[profile.release.build-override]
opt-level = 0
